wordpress:
  image: wordpress
  links:
    - wordpress_db:mysql
  ports:
    - "8082:80"
wordpress_db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: kalinga
phpadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - wordpress_db:mysql
  ports:
    - "8083:80"
  environment:
    MYSQL_USERNAME: kalinga
    MYSQL_ROOT_PASWORD: kalinga
